# Generated by Django 2.2.4 on 2020-09-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Network', models.CharField(max_length=255)),
                ('Release_date', models.DateField()),
                ('Description', models.TextField(default='')),
            ],
        ),
    ]
